### ISSUE TITLE
留言板 | 洪卫的博客

### ISSUE THREAD

**Issue by shw2018** [shw2018/shw2018.github.io#1]
https://shw2018.github.io/contact/ 

 留言板 | 洪卫的博客

**Comment by shw2018** [comment]
一楼测试

**Comment by godweiyang** [comment]
兄弟你的博客可以复制我的源代码，但是文章最好别用我的啊，删了吧

**Comment by shw2018** [comment]
> 兄弟你的博客可以复制我的源代码，但是文章最好别用我的啊，删了吧

你好，我是看你的教程点进你的厂库下载的，你教程本来有提供链接，至于你的文章我大部分都删除了的，留下几篇是为了这几天调试看页面效果，你的文章除了教程这一篇，其他对我也没多大价值，今天全部删除了 ，开始自己写了，请不要误解，谢谢！至于源码，你也是用的原作者Blinkfox的主题，hexo博客框架本来就是开源的，你只是改了一些源文件的参数，所以，让人哭笑不得，先给你说声谢谢吧！

**Comment by godweiyang** [comment]
> > 兄弟你的博客可以复制我的源代码，但是文章最好别用我的啊，删了吧
> 
> 你好，我是看你的教程点进你的厂库下载的，你教程本来有提供链接，至于你的文章我大部分都删除了的，留下几篇是为了这几天调试看页面效果，你的文章除了教程这一篇，其他对我也没多大价值，今天全部删除了 ，开始自己写了，请不要误解，谢谢！至于源码，你也是用的原作者Blinkfox的主题，hexo博客框架本来就是开源的，你只是改了一些源文件的参数，所以，让人哭笑不得，先给你说声谢谢吧！

okok，我的锅兄弟，主要我就看你把教程改成自己名字了，其他没啥，源码我肯定改了些bug的。都是误会，加油吧，祝你多发论文，多写些cv和深度学习也让我学习学习

**Comment by shw2018** [comment]
> > > 兄弟你的博客可以复制我的源代码，但是文章最好别用我的啊，删了吧
> > 
> > 
> > 你好，我是看你的教程点进你的厂库下载的，你教程本来有提供链接，至于你的文章我大部分都删除了的，留下几篇是为了这几天调试看页面效果，你的文章除了教程这一篇，其他对我也没多大价值，今天全部删除了 ，开始自己写了，请不要误解，谢谢！至于源码，你也是用的原作者Blinkfox的主题，hexo博客框架本来就是开源的，你只是改了一些源文件的参数，所以，让人哭笑不得，先给你说声谢谢吧！
> 
> okok，我的锅兄弟，主要我就看你把教程改成自己名字了，其他没啥，源码我肯定改了些bug的。都是误会，加油吧，祝你多发论文，多写些cv和深度学习也让我学习学习

喔喔，谢谢你的祝愿，相互学习。然后，根目录配置yml文件参数，将博客author名字改变后，所有文章作者都会自动变，是全局参数，不好意思，是个误会。早点休息吧，晚安！
